#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_report.py — Script bổ trợ cho skill /bd-weekly-report
Đọc file export JSON từ BD Manager, tạo báo cáo markdown.
Usage: python3 gen_report.py <input.json> <output.md>
"""
import json, sys, os
from datetime import datetime, timedelta

STAGES = ['MQL','SAL','SQL','CONTRACT','CUS','FAIL']
STAGE_NAMES = {'MQL':'MQL','SAL':'SAL','SQL':'SQL','CONTRACT':'Hợp đồng','CUS':'Đã chốt','FAIL':'Lost'}
PROB = {'MQL':20,'SAL':40,'SQL':60,'CONTRACT':80,'CUS':100,'FAIL':0}

def fmt(n):
    return f"{int(n):,}".replace(",",".")

def parse_date(s):
    if not s: return None
    try: return datetime.fromisoformat(s.replace('Z','+00:00'))
    except: return None

def main():
    if len(sys.argv) < 3:
        print("Usage: python3 gen_report.py input.json output.md")
        sys.exit(1)

    with open(sys.argv[1], encoding='utf-8') as f:
        data = json.load(f)

    deals = data.get('deals', [])
    tasks = data.get('tasks', [])
    exported_at = parse_date(data.get('exportedAt')) or datetime.now()
    now = datetime.now()

    # Week bounds
    week_num = now.isocalendar()[1]
    year = now.year
    week_start = now - timedelta(days=now.weekday())
    week_end   = week_start + timedelta(days=6)

    # ── Deal analysis
    stage_counts = {s:0 for s in STAGES}
    stage_values = {s:0 for s in STAGES}
    pipeline_value = 0
    closed_value   = 0
    upcoming_appts = []

    for d in deals:
        s = d.get('stage','MQL')
        stage_counts[s] = stage_counts.get(s,0) + 1
        v = d.get('value', 0) or 0
        stage_values[s] = stage_values.get(s,0) + v
        if s not in ('CUS','FAIL'):
            pipeline_value += v * PROB.get(s,50) / 100
        if s == 'CUS':
            closed_value += v
        # Upcoming appointment
        appt = parse_date(d.get('appointment'))
        if appt and now <= appt <= now + timedelta(days=7):
            upcoming_appts.append((appt, d.get('name',''), d.get('company','')))

    upcoming_appts.sort()

    # ── Task analysis
    overdue_tasks   = []
    done_this_week  = []
    upcoming_tasks  = []

    for t in tasks:
        status   = t.get('status','todo')
        due      = parse_date(t.get('dueDate'))
        updated  = parse_date(t.get('updatedAt'))
        title    = t.get('title','')

        if status != 'done' and due and due < now:
            overdue_tasks.append((due, title))
        if status == 'done' and updated and week_start.replace(tzinfo=None) <= updated.replace(tzinfo=None):
            done_this_week.append(title)
        if status != 'done' and due and now <= due <= now + timedelta(days=7):
            upcoming_tasks.append((due, title))

    overdue_tasks.sort()
    upcoming_tasks.sort()

    # ── Build report
    lines = [
        f"# BÁO CÁO BD TUẦN {week_num}/{year}",
        f"**Từ:** {week_start.strftime('%d/%m/%Y')} — **Đến:** {week_end.strftime('%d/%m/%Y')}",
        f"*Xuất lúc: {now.strftime('%d/%m/%Y %H:%M')}*",
        "",
        "---",
        "",
        "## 📊 Tổng quan Pipeline",
        "",
        "| Giai đoạn | Số deal | Giá trị (VNĐ) |",
        "|---|---|---|",
    ]
    for s in STAGES:
        if stage_counts[s]:
            lines.append(f"| {STAGE_NAMES[s]} | {stage_counts[s]} | {fmt(stage_values[s])} |")

    lines += [
        "",
        "## 💰 Doanh thu",
        f"- **Pipeline dự kiến** (theo xác suất): **{fmt(pipeline_value)} VNĐ**",
        f"- **Đã chốt** (CUS): **{fmt(closed_value)} VNĐ**",
        "",
        "---",
        "",
        "## ✅ Tình trạng Task",
        f"- Hoàn thành trong tuần: **{len(done_this_week)} task**",
        f"- Quá hạn: **{len(overdue_tasks)} task**",
        f"- Sắp đến hạn (7 ngày tới): **{len(upcoming_tasks)} task**",
        "",
    ]

    if overdue_tasks:
        lines.append("### 🔴 Task quá hạn cần xử lý ngay")
        for due, title in overdue_tasks:
            lines.append(f"- [ ] **{title}** _(hạn: {due.strftime('%d/%m/%Y')})_")
        lines.append("")

    if upcoming_tasks:
        lines.append("### 🟡 Task sắp đến hạn (7 ngày tới)")
        for due, title in upcoming_tasks:
            lines.append(f"- [ ] {title} _(hạn: {due.strftime('%d/%m/%Y')})_")
        lines.append("")

    if done_this_week:
        lines.append("### 🟢 Đã hoàn thành trong tuần")
        for title in done_this_week:
            lines.append(f"- [x] {title}")
        lines.append("")

    lines += ["---", "", "## 📅 Lịch hẹn sắp tới (7 ngày)"]
    if upcoming_appts:
        for appt, name, company in upcoming_appts:
            lines.append(f"- **{appt.strftime('%d/%m %H:%M')}** — {name} ({company})")
    else:
        lines.append("_(Không có lịch hẹn trong 7 ngày tới)_")

    lines += ["", "---", "", "*Generated by BD Manager · /bd-weekly-report*"]

    out_path = sys.argv[2]
    os.makedirs(os.path.dirname(out_path) if os.path.dirname(out_path) else '.', exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"OK: {out_path}")
    print(f"  Deals active : {sum(stage_counts[s] for s in STAGES if s not in ('CUS','FAIL'))}")
    print(f"  Pipeline     : {fmt(pipeline_value)} VND")
    print(f"  Closed       : {fmt(closed_value)} VND")
    print(f"  Overdue tasks: {len(overdue_tasks)}")

if __name__ == '__main__':
    main()
